### ISSUE TITLE
Type Error (Keyword "apply_as" unrecognized)

### ISSUE THREAD

**Issue by DenisLabrecque** [oormicreations/BlendShell#1]
Using the latest release, I made a simple mesh and tested this addon. I was unable to make it work due to the following error (using Windows 10, Blender 2.90.1). Help would be appreciated as it looks like a very useful tool that could save me time.

```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blendshell-03.py", line 214, in execute
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier="Smooth")
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1
```

**Comment by DenisLabrecque** [comment]
This was my model and settings:
![image](https://user-images.githubusercontent.com/11930465/96630609-e3dcc900-12da-11eb-95e1-feb498c6f6fa.png)
The seed is inside the model. I noticed that a smooth modifier gets added to the seed's stack every time, so I removed it and tried with different settings, but this is an uncaught exception.

**Comment by oormicreations** [comment]
This is a known issue, but thank you for reminding me.
Blender 2.90 onward there was a change in the way modifiers work, so far this addon has not implemented it.
Please try it in a lower version. E.g. 2.82
Secondly, it is designed to work with organic models. It will work with hard surface models (geometric shapes) but it is recommended to hollow them out via modelling or shell modifier for best results.
Also, please try it with the supplied model of the dog, to get an idea of parameters etc.

**Comment by lidorshimoni** [comment]
please fix :)

**Comment by PashaWNN** [comment]
@lidorshimoni as soon as I have free time I'll try
